
enableAntiAffinity: false
enableTls: false
enableTokenAuth: false
fixRootlessPermissions:
  enabled: true
restartOnConfigMapChange:
  enabled: true
extra:
  function: true
  burnell: true
  burnellLogCollector: true
  pulsarHeartbeat: true
  pulsarAdminConsole: true

zookeeper:
  replicaCount: 1
  resources:
    requests:
      memory: 300Mi
      cpu: 1
  configData:
    PULSAR_MEM: "\"-Xms300m -Xmx300m -Djute.maxbuffer=10485760 -XX:+ExitOnOutOfMemoryError\""

bookkeeper:
  replicaCount: 1
  resources:
    requests:
      memory: 4Gi
      cpu: 1
  configData:
    BOOKIE_MEM: "\"-Xms2g -Xmx2g -XX:MaxDirectMemorySize=1500m -XX:+ExitOnOutOfMemoryError\""

broker:
  component: broker
  replicaCount: 1
  ledger:
    defaultEnsembleSize: 1
    defaultAckQuorum: 1
    defaultWriteQuorum: 1
  resources:
    requests:
      memory: 600Mi
      cpu: 1
  configData:
    PULSAR_MEM: "\"-Xms400m -Xmx400m -XX:MaxDirectMemorySize=200m -XX:+ExitOnOutOfMemoryError\""
  functionsWorkerEnabled: true

autoRecovery:
  enableProvisionContainer: true
  resources:
    requests:
      memory: 300Mi
      cpu: 1

function:
  replicaCount: 0
  functionReplicaCount: 0
  resources:
    requests:
      memory: 512Mi
      cpu: 1
  configData:
    PULSAR_MEM: "\"-Xms312m -Xmx312m -XX:MaxDirectMemorySize=200m -XX:+ExitOnOutOfMemoryError\""
  authenticationEnabled: false
  authorizationEnabled: false

proxy:
  replicaCount: 1
  resources:
    requests:
      memory: 512Mi
      cpu: 1
  wsResources:
    requests:
      memory: 512Mi
      cpu: 1
  configData:
    PULSAR_MEM: "\"-Xms400m -Xmx400m -XX:MaxDirectMemorySize=112m\""
  autoPortAssign:
    enablePlainTextWithTLS: true
  service:
    autoPortAssign:
      enabled: true

grafanaDashboards:
  enabled: true

pulsarAdminConsole:
  replicaCount: 1
  authMode: k8s
  createUserSecret:
    enabled: true
    user: 'admin'
    password: 'admin'

kube-prometheus-stack:
  enabled: true
  prometheusOperator:
    enabled: true
  grafana:
    enabled: true
    adminPassword: admin
