apiVersion: batch/v1
kind: Job
metadata:
  name: dsbulk-load-meteorite-data
spec:
  template:
    spec:
      containers:
      - name: dsbulk
        image: docker.io/jamesc127/meteorite-landings:0.12
        env:
        - name: CASS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cdc-test-superuser
              key: password
        - name: CASS_USERNAME
          valueFrom:
            secretKeyRef:
              name: cdc-test-superuser
              key: username
      restartPolicy: OnFailure
